### PR TITLE
Bugfix/#69 fix action pipeline deadlocks and other issues that cause random action cancelations.

### LINKED ISSUE #68: Fix action locking issue that causes an invalid transition from rejected to aborted
Once the registration test count of the `testPowerStateServicePerformance` is increased from `100` to `1000` we run into an invalid transition from rejected to abording. Investigate test and fix issue. 

The remote connection gets lost since the controller seems to be to busy.

```
21:35:55.042 [pool-1-thread-93] WARN  o.o.b.d.r.l.u.PowerSwitchRemote Remote connection to Controller[/location-1/powerswitch/powerswitch-1] lost!
21:35:59.729 [pool-1-thread-97] ERROR o.o.b.d.c.a.ActionImpl Can not finalize ActionImpl[action-normal-8ebaf922|POWER_STATE_SERVICE|{"value": "ON"}|powerswitch-ea87da4a|user-bco-f19a7c8d(SYSTEM)|INITIATING] it seems the execution has stuck.
21:35:59.735 [pool-1-thread-97] WARN  o.o.b.d.c.a.ActionImpl Can not change the state to ABORTING of an already rejected action!
21:35:59.736 [pool-1-thread-97] WARN  o.o.b.d.c.a.ActionImpl 
=== Stacktrace ===
org.openbase.jul.exception.StackTracePrinter.printStackTrace(StackTracePrinter.java:72)
org.openbase.bco.dal.control.action.ActionImpl.updateActionState(ActionImpl.java:763)
org.openbase.bco.dal.control.action.ActionImpl.updateActionStateWhileHoldingWriteLock(ActionImpl.java:744)
org.openbase.bco.dal.control.action.ActionImpl.abort(ActionImpl.java:559)
org.openbase.bco.dal.lib.action.SchedulableAction.abort(SchedulableAction.java:64)
org.openbase.bco.dal.control.layer.unit.AbstractUnitController.reschedule(AbstractUnitController.java:1080)
org.openbase.bco.dal.control.layer.unit.AbstractUnitController.scheduleAction(AbstractUnitController.java:858)
org.openbase.bco.dal.control.layer.unit.AbstractUnitController.applyAction(AbstractUnitController.java:675)
org.openbase.bco.dal.control.layer.unit.AbstractUnitController.internalApplyActionAuthenticated(AbstractUnitController.java:1278)
org.openbase.bco.dal.control.layer.unit.AbstractUnitController.lambda$applyActionAuthenticated$5(AbstractUnitController.java:1226)
org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:135)
org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:90)
org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:69)
org.openbase.bco.dal.control.layer.unit.AbstractUnitController.applyActionAuthenticated(AbstractUnitController.java:1244)
jdk.internal.reflect.GeneratedMethodAccessor760.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
org.openbase.jul.communication.mqtt.RPCMethod.invoke(RPCMethod.kt:223)
org.openbase.jul.communication.mqtt.RPCServerImpl.handleRemoteCall(RPCServerImpl.kt:141)
org.openbase.jul.communication.mqtt.RPCServerImpl.activate$lambda-2$lambda-1(RPCServerImpl.kt:65)
com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303)
com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288)
com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:406)
com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:235)
com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:200)
io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649)
io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:833)
==================
21:35:59.739 [pool-1-thread-97] INFO  o.o.j.p.JPVerbose Verbose is enabled!
21:35:59.742 [pool-1-thread-97] INFO  o.o.b.d.c.l.u.PowerSwitchController ActionImpl[action-normal-bdc604a5|POWER_STATE_SERVICE|{"value": "OFF"}|powerswitch-ea87da4a|user-bco-f19a7c8d(SYSTEM)|REJECTED] was postponed because of ActionImpl[action-termination-economy-0b796e97|POWER_STATE_SERVICE|{"value": "OFF"}|powerswitch-ea87da4a|user-bco-f19a7c8d(SYSTEM)|SUBMISSION] and added to the scheduling queue of PowerSwitchController[POWER_SWITCH[PW Power Plug Device]] at position 36.
21:35:59.745 [pool-1-thread-989] INFO  o.o.b.d.c.l.u.PowerSwitchController PW Power Plug Device is updated from off to off.
21:35:59.745 [pool-1-thread-97] ERROR o.o.b.a.l.AuthenticatedServerManager ═══⚀ Request timestamp [21.7.2022 - 21:35:54:89] differs more than 5 seconds from server time [21.7.2022 - 21:35:59:743]
21:35:59.746 [pool-1-thread-97] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
21:35:59.749 [pool-1-thread-97] ERROR o.o.b.a.l.AuthenticatedServerManager Request timestamp [21.7.2022 - 21:35:54:89] differs more than 5 seconds from server time [21.7.2022 - 21:35:59:743]
org.openbase.bco.authentication.lib.exception.SessionExpiredException: Request timestamp [21.7.2022 - 21:35:54:89] differs more than 5 seconds from server time [21.7.2022 - 21:35:59:743]
	at org.openbase.bco.authent
```

### LINKED ISSUE #69: testAbsenceEnergySavingAgent fails with execution state can not be reached.
Test fails with:
```
org.openbase.jul.exception.CouldNotPerformException: PH Hue E27 Device Stairway - stop waiting because state[EXECUTING] cannot be reached from state[REJECTED]
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForActionState(RemoteAction.java:1017)
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForActionState(RemoteAction.java:997)
	at app//org.openbase.bco.dal.remote.action.RemoteAction.waitForActionState(RemoteAction.java:973)
	at app//org.openbase.bco.dal.test.AbstractBCOTest.waitForExecution(AbstractBCOTest.java:217)
	at app//org.openbase.bco.app.preset.agent.AbsenceEnergySavingAgentTest.testAbsenceEnergySavingAgent(AbsenceEnergySavingAgentTest.java:112)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Issue can as well be reproduced by: 
```
org.openbase.bco.dal.test.layer.unit.scene.SceneRemoteTest

  Test testTriggerSceneWithLocationActionPerRemoteAndVerifiesUnitModification() FAILED (4.5s)

  org.openbase.jul.exception.CouldNotPerformException: location On Test Scene - stop waiting because state[EXECUTING] cannot be reached from state[REJECTED]
      at app//org.openbase.bco.dal.test.layer.unit.scene.SceneRemoteTest.testTriggerSceneWithLocationActionPerRemoteAndVerifiesUnitModification(SceneRemoteTest.java:576)

  Test testTriggerSceneWithAllDevicesOfLocationActionPerRemoteAndVerifiesUnitModification() FAILED (2.9s)

  org.openbase.jul.exception.CouldNotPerformException: location Devices On Test Scene - stop waiting because state[EXECUTING] cannot be reached from state[REJECTED]
      at app//org.openbase.bco.dal.test.layer.unit.scene.SceneRemoteTest.testTriggerSceneWithAllDevicesOfLocationActionPerRemoteAndVerifiesUnitModification(SceneRemoteTest.java:509)

      Test testIntermediaryActionCancellationOnSceneDeactivation() FAILED (1.8s)
```

### LINKED ISSUE #70: fix testThatScenesDoNotInterfereEachOther() test
Fails with:
```
org.opentest4j.AssertionFailedError: Light is not red but: BCO changed power of PH Hue E27 Device Stairway to off. ==> expected: <type: HSB
hsb_color {
  hue: 0.0
  saturation: 1.0
  brightness: 1.0
}
> but was: <type: HSB
hsb_color {
  hue: 0.0
  saturation: 1.0
  brightness: 0.0
}
>
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
	at app//org.openbase.bco.dal.test.layer.unit.scene.SceneRemoteTest.testThatScenesDoNotInterfereEachOther(SceneRemoteTest.java:855)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at app//org.junit.platfor
```
output
```
?[0;39m17:50:57.643 [pool-1-thread-3] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mGroup Trigger Scene is updated from unknown to inactive.
?[0;39m17:50:57.647 [pool-1-thread-3] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Group Trigger Scene to inactive.
?[0;39m17:50:57.654 [pool-1-thread-47] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.UnitControllerRegistrySynchronizer?[0;39m ?[39m1 changes synchronized.
?[0;39m17:50:57.672 [pool-1-thread-40] ?[34mINFO ?[0;39m ?[36mo.o.j.p.JPTestMode?[0;39m ?[39mTest mode enabled!
?[0;39m17:50:57.879 [pool-1-thread-82] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mBlue Test Scene is updated from inactive to active.
?[0;39m17:50:57.976 [pool-1-thread-88] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Heaven is updated from black to blue.
?[0;39m17:50:58.013 [pool-1-thread-88] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Heaven to blue.
?[0;39m17:50:58.014 [pool-1-thread-37] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Hell is updated from black to blue.
?[0;39m17:50:58.019 [pool-1-thread-59] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device is updated from black to blue.
?[0;39m17:50:58.068 [pool-1-thread-61] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Stairway is updated from black to blue.
?[0;39m17:50:58.104 [pool-1-thread-37] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Hell to blue.
?[0;39m17:50:58.143 [pool-1-thread-59] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device to blue.
?[0;39m17:50:58.174 [pool-1-thread-61] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Stairway to blue.
?[0;39m17:50:58.580 [pool-1-thread-82] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Blue Test Scene to active.
?[0;39m17:50:59.055 [pool-1-thread-82] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mRed Test Scene is updated from inactive to active.
?[0;39m17:50:59.264 [pool-1-thread-100] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Hell is updated from blue to red.
?[0;39m17:50:59.311 [pool-1-thread-26] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device is updated from blue to red.
?[0;39m17:50:59.332 [pool-1-thread-87] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Heaven is updated from blue to red.
?[0;39m17:50:59.336 [pool-1-thread-71] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Stairway is updated from blue to red.
?[0;39m17:50:59.340 [pool-1-thread-100] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Hell to red.
?[0;39m17:50:59.377 [pool-1-thread-87] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Heaven to red.
?[0;39m17:50:59.385 [pool-1-thread-26] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device to red.
?[0;39m17:50:59.385 [pool-1-thread-71] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Stairway to red.
?[0;39m17:50:59.880 [pool-1-thread-82] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Red Test Scene to active.
?[0;39m17:51:00.032 [pool-1-thread-76] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mBlue Test Scene is updated from active to inactive.
?[0;39m17:51:00.895 [pool-1-thread-76] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Blue Test Scene to inactive.
?[0;39m17:51:01.166 [pool-1-thread-25] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mBlue Test Scene is updated from inactive to active.
?[0;39m17:51:01.482 [pool-1-thread-24] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device is updated from red to blue.
?[0;39m17:51:01.493 [pool-1-thread-91] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Stairway is updated from red to blue.
?[0;39m17:51:01.508 [pool-1-thread-92] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Hell is updated from red to blue.
?[0;39m17:51:01.558 [pool-1-thread-67] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Heaven is updated from red to blue.
?[0;39m17:51:01.571 [pool-1-thread-91] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Stairway to blue.
?[0;39m17:51:01.592 [pool-1-thread-24] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device to blue.
?[0;39m17:51:01.595 [pool-1-thread-92] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Hell to blue.
?[0;39m17:51:01.656 [pool-1-thread-67] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Heaven to blue.
?[0;39m17:51:02.191 [pool-1-thread-25] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Blue Test Scene to active.
?[0;39m17:51:02.355 [pool-1-thread-37] ?[33mWARN ?[0;39m ?[36mo.o.b.d.r.l.u.l.LocationRemote?[0;39m ?[33mRemote connection to Controller[/location-1] lost!
?[0;39m17:51:03.188 [pool-1-thread-46] ?[34mINFO ?[0;39m ?[36mo.o.b.d.r.l.u.l.LocationRemote?[0;39m ?[39mConnection reestablished LocationRemote[scope:/location-1]
?[0;39m17:51:03.201 [pool-1-thread-70] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mBlue Test Scene is updated from active to inactive.
?[0;39m17:51:03.436 [pool-1-thread-79] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device is updated from blue to red.
?[0;39m17:51:03.438 [pool-1-thread-77] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Stairway is updated from blue to red.
?[0;39m17:51:03.496 [pool-1-thread-79] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device to red.
?[0;39m17:51:03.505 [pool-1-thread-77] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Stairway to red.
?[0;39m17:51:03.534 [pool-1-thread-89] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Hell is updated from blue to red.
?[0;39m17:51:03.611 [pool-1-thread-88] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Heaven is updated from blue to red.
?[0;39m17:51:03.634 [pool-1-thread-89] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Hell to red.
?[0;39m17:51:03.656 [pool-1-thread-88] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed color of PH Hue E27 Device Heaven to red.
?[0;39m17:51:04.057 [pool-1-thread-59] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mRed Test Scene is updated from active to inactive.
?[0;39m17:51:04.195 [pool-1-thread-66] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Hell is updated from on to off.
?[0;39m17:51:04.221 [pool-1-thread-66] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of PH Hue E27 Device Hell to off.
?[0;39m17:51:04.252 [pool-1-thread-92] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Stairway is updated from on to off.
?[0;39m17:51:04.265 [pool-1-thread-44] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device Heaven is updated from on to off.
?[0;39m17:51:04.334 [pool-1-thread-92] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of PH Hue E27 Device Stairway to off.
?[0;39m17:51:04.347 [pool-1-thread-81] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.ColorableLightController?[0;39m ?[39mPH Hue E27 Device is updated from on to off.
?[0;39m17:51:04.349 [pool-1-thread-44] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of PH Hue E27 Device Heaven to off.
?[0;39m17:51:04.383 [pool-1-thread-81] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of PH Hue E27 Device to off.
?[0;39m17:51:04.425 [pool-1-thread-70] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Blue Test Scene to inactive.
?[0;39m17:51:04.539 [Test worker] ?[34mINFO ?[0;39m ?[36mo.o.b.d.t.l.u.s.SceneRemoteTest?[0;39m ?[39mCancel all ongoing actions...
?[0;39m17:51:04.551 [pool-1-thread-48] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.DimmerController?[0;39m ?[39mHA TYA663A Device is updated from off to off.
?[0;39m17:51:04.553 [pool-1-thread-48] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of HA TYA663A Device to off.
?[0;39m17:51:04.567 [pool-1-thread-66] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.DimmableLightController?[0;39m ?[39mHA ABC Device is updated from off to off.
?[0;39m17:51:04.586 [pool-1-thread-66] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of HA ABC Device to off.
?[0;39m17:51:04.609 [pool-1-thread-74] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.LightController?[0;39m ?[39mF FGS221 Device is updated from off to off.
?[0;39m17:51:04.611 [pool-1-thread-74] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of F FGS221 Device to off.
?[0;39m17:51:04.663 [pool-1-thread-52] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.PowerSwitchController?[0;39m ?[39mPW Power Plug Device is updated from off to off.
?[0;39m17:51:04.666 [pool-1-thread-52] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of PW Power Plug Device to off.
?[0;39m17:51:04.788 [Test worker] ?[34mINFO ?[0;39m ?[36mo.o.b.d.t.AbstractBCOTest?[0;39m ?[39mCancel 3 ongoing test actions ...
?[0;39m17:51:04.864 [pool-1-thread-97] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.s.SceneControllerImpl?[0;39m ?[39mBlue Test Scene is updated from inactive to inactive.
?[0;39m17:51:04.886 [pool-1-thread-97] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed activation of Blue Test Scene to inactive.
?[0;39mtestTriggerSceneWithLocationActionPerRemoteAndVerifiesUnitModification
17:51:05.011 [pool-1-thread-6] ?[34mINFO ?[0;39m ?[36mo.o.j.p.JPTestMode?[0;39m ?[39mTest mode enabled!
?[0;39m17:51:05.059 [pool-1-thread-80] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.l.u.LightController?[0;39m ?[39mF FGS221 Device is updated from off to on.
?[0;39m17:51:05.059 [pool-1-thread-80] ?[34mINFO ?[0;39m ?[36mo.o.b.d.c.a.ActionImpl?[0;39m ?[39mBCO changed power of F FGS221 Device to on.
```
Generated by [Gradle 7.5](http://www.gradle.org/) at Aug 5, 2022, 5:51:11 PM

### LINKED ISSUE #83: Fix Location Controller Deadlocks
The current beta release stuck after a while because of location controller deadlocks.
* investigate deadlock
* provide solution.

### PR DESCRIPTION
**Pull request by DivineThreepwood**
### :scroll: Description

Changes proposed in this pull request:
* fix potential deadlock between actionDescriptionBuilderLock and actionTaskLock in ActionImpl.
* make sure reschedule is not triggered once the unit controller is shutting down to avoid lots of exceptions.
* Make sure required state observer is shutdown in case the scene state changes to not interfere with future scene activations. Improve required state validation by filtering by validate the initial action to avoid scene cancelation based on an outdated action. Minor typo fixes.
* fix logic issue in equalServiceStates check.
* Implement validateInitialAction service method for Actions.
* Make sure remote action cleanup task does not cleanup the state of other actions that are later observed by the same remote instance, by canceling the cleanup task once the remote is reinitialized.
* make sure remote action list is always locked once accessed.
* Code readability improvements.
* clearly define start and end of an bco test to enable the separation of test prints vs. setup / cleanup prints.
* improve test logging.

### CODE REVIEW

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/action/ActionImpl.java [hunk 1]
```diff
@@ -68,6 +68,9 @@ public class ActionImpl implements SchedulableAction {
 
     protected final AbstractUnitController<?, ?> unit;
     private final SyncObject executionStateChangeSync = new SyncObject("ExecutionStateChangeSync");
+
+    // any code that accesses the data lock while holding the action task lock should previously lock the data lock.
+    // otherwise deadlocks can occur.
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/action/ActionImpl.java]: This comment is not entirely clear to me, especially with regard to the proposed change below. There are two possibilities:
1. We always need to acquire the data lock if we need the the action task lock and the data lock has to be acquired first.
2. We don't need to acquire the data lock in every case we need the action task look. But if we do, the data lock has to be acquired first.

I think you mean option 2. But in light of the proposed change below, this is not easily visible since the requirement to acquire the data lock is hidden in the `isTerminating()` call.

In general, I think the usage of such a comment is sub-optimal as you will not see this comment during coding. Would it be possible to implement a structure where when you acquire the action task lock, you have to consciously decide if you also need to acquire the data lock?

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 2]
```diff
@@ -305,10 +313,10 @@ public synchronized Future<ActionDescription> setActivationState(final Activatio
                                 requiredActionImpactList.addAll(requiredAction.getActionImpact(true));
 
                             } catch (org.openbase.jul.exception.TimeoutException ex) {
-                                // if the timeout is exhausted than just continue since we want to keep on trying as long as the scene is active.
+                                // if the timeout is exhausted then just continue since we want to keep on trying as long as the scene is active.
                                 continue;
                             } catch (CancellationException | CouldNotPerformException ex) {
-                                ExceptionPrinter.printHistory("Optional " + requiredAction + " of " + this + " could not executed!", ex, logger, LogLevel.WARN);
+                                ExceptionPrinter.printHistory("Required " + requiredAction + " of " + getLabel("?") + " could not executed!", ex, logger, LogLevel.DEBUG);
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]:
```suggestion
                                ExceptionPrinter.printHistory("Required " + requiredAction + " of " + getLabel("?") + " could not be executed!", ex, logger, LogLevel.DEBUG);
```

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 3]
```diff
@@ -321,14 +329,14 @@ public synchronized Future<ActionDescription> setActivationState(final Activatio
                                 // if the timeout is exhausted than just continue since we want to keep on trying as long as the scene is active.
                                 continue;
                             } catch (CancellationException | CouldNotPerformException ex) {
-                                ExceptionPrinter.printHistory("Optional " + optionalAction + " of " + this + " could not executed!", ex, logger, LogLevel.WARN);
+                                ExceptionPrinter.printHistory("Optional " + optionalAction + " of " + getLabel("?") + " could not executed!", ex, logger, LogLevel.TRACE);
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]:
```suggestion
                                ExceptionPrinter.printHistory("Optional " + optionalAction + " of " + getLabel("?") + " could not be executed!", ex, logger, LogLevel.TRACE);
```

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 4]
```diff
@@ -321,14 +329,14 @@ public synchronized Future<ActionDescription> setActivationState(final Activatio
...
                             }
                         }
 
                         // register an observer which will deactivate the scene if one required action is now longer running
                         // observer will cleanup itself after the action is no longer valid so no need to care fore it.
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]: I guess the second line of this comment is now outdated and should be removed.

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 5]
```diff
@@ -427,6 +437,7 @@ private RequiredActionObserver(final List<ActionReference> requiredActionImpact,
 
         private void verifyAllStates() {
             try {
+                // logger.trace("verify "+unitAndRequiredServiceStateMap.entrySet().size()+ " states of "+ getLabel("?"));
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]: Maybe remove commented debug log

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 6]
```diff
@@ -446,12 +457,25 @@ private void verifyAllStates() {
...
         private void verifyState(final ServiceProvider<? extends Message> unit, final Message serviceState) throws VerificationFailedException {
 
+            // skip verification on destroyed required action observer!
+            if(destroy) {
+                return;
+            }
+
             if (!responsibleAction.isValid()) {
-                throw new VerificationFailedException("Action not valid anymore!");
+                throw new VerificationFailedException("The activation of "+getLabel("?") + " is not valid anymore.");
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]: This line is not properly formatted. Maybe re-run automatic formatting on this file.

```suggestion
                throw new VerificationFailedException("The activation of " + getLabel("?") + " is not valid anymore.");
```

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 7]
```diff
@@ -446,12 +457,25 @@ private void verifyAllStates() {
...
+            }
+
+            // skip in case to service state was delivered
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]:
```suggestion
            // skip in case no service state was delivered
```

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 8]
```diff
@@ -446,12 +457,25 @@ private void verifyAllStates() {
...
+            if(serviceState.toString().isBlank()) {
+                return;
             }
 
             if (!Services.equalServiceStates(unitAndRequiredServiceStateMap.get(unit).getServiceState(), serviceState)) {
-                throw new VerificationFailedException("State of " + unit + "not meet!");
+                // LOGGER.warn(unitAndRequiredServiceStateMap.get(unit).getServiceState() + " is not equals " + serviceState.toString().substring(0, 20) + " and will cancel: " + SceneControllerImpl.this.getLabel("?"));
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]: Maybe remove commented log

File: module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java [hunk 9]
```diff
@@ -469,6 +493,7 @@ private void unsatisfiedState() {
         @Override
         public void update(ServiceStateProvider<Message> serviceStateProvider, Message serviceState) throws Exception {
             try {
+                // logger.error("Incomming service state update from "+ serviceStateProvider.getServiceProvider().getId() + " triggered from "+ serviceState.toString());
```
Comment (pLeminoq) [inline module/dal/control/src/main/java/org/openbase/bco/dal/control/layer/unit/scene/SceneControllerImpl.java]: Maybe remove commented log

File: module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/Actions.java [hunk 10]
```diff
@@ -55,4 +58,27 @@ public static RemoteAction waitForActionState(final Future<ActionDescription> ac
         remoteAction.waitForActionState(actionState, timeout, timeUnit);
         return remoteAction;
     }
+
+    public static boolean validateInitialAction(Message serviceState) {
+        try {
+            return validateInitialAction(ServiceStateProcessor.getResponsibleAction(serviceState));
+        } catch (CouldNotPerformException e) {
+            // skip validation is error case.
```
Comment (pLeminoq) [inline module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/Actions.java]:
```suggestion
            // skip validation in error case.
```

File: module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/RemoteAction.java [hunk 11]
```diff
@@ -259,7 +261,7 @@ public Future<ActionDescription> execute(final ActionDescriptionOrBuilder causeA
             }
 
             if (force) {
-                // we do not need to cancel a running actions because its rejected on the target unit anyway when a the new action is executed.
+                // we do not need to cancel a running actions because its rejected on the target unit anyway when the new action is executed.
```
Comment (pLeminoq) [inline module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/RemoteAction.java]:
```suggestion
                // we do not need to cancel a running action because it is rejected on the target unit anyway when the new action is executed.
```

File: module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/RemoteAction.java [hunk 12]
```diff
@@ -1213,24 +1217,25 @@ public ActionParameter getActionParameter() throws NotAvailableException {
...
+            description = ActionDescriptionProcessor.toString(actionReference);
+        }
 
-            // resolve via parameter
-            if (actionParameter != null) {
-                return ActionDescriptionProcessor.toString(actionParameter);
-            }
+        // resolve via parameter
+        if (description == null && actionParameter != null) {
+            description = ActionDescriptionProcessor.toString(actionParameter);
```
Comment (pLeminoq) [inline module/dal/remote/src/main/java/org/openbase/bco/dal/remote/action/RemoteAction.java:1235]: Since the `description` is set to an empty string above you `description.isEmpty()` should be used instead of the null checks.

File: module/dal/test/src/test/java/org/openbase/bco/dal/test/layer/unit/scene/SceneRemoteTest.java [hunk 13]
```diff
@@ -585,7 +587,9 @@ public void testTriggerSceneWithLocationActionPerRemoteAndVerifiesUnitModificati
             assertEquals(State.ACTIVE, sceneRemoteOn.getActivationState().getValue(), "Location on scene is not active");
             assertEquals(State.INACTIVE, sceneRemoteOff.getActivationState().getValue(), "Location off scene is not inactive");
 
+            LOGGER.warn("turn off...");
             waitForExecution(sceneRemoteOff.setActivationState(State.ACTIVE, SCENE_ACTION_PARAM));
+            LOGGER.warn("turn off... continue");
```
Comment (pLeminoq) [inline module/dal/test/src/test/java/org/openbase/bco/dal/test/layer/unit/scene/SceneRemoteTest.java]: Are these debugging logs still required?

**Review by pLeminoq — CHANGES_REQUESTED** [review]
Overall, a really nice PR. I just have suggestions for a few minor changes and I think the actionTask issue has to be discussed.

**Comment by DivineThreepwood** [comment]
Thanks for the detailed review. All conversations are addressed, so PR is ready to review again.

**Review by pLeminoq — APPROVED** [review]
